[package]
name = "iconfinder"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
bitcode = "0.6.3"
regex = "1.11.1"
serde_json = "1.0.132"
strsim = "0.11.1"
